"""
joint_map.py

AUTO-GENERATED by urdf_joint_map.py from assembly_1.urdf.
Re-run `python urdf_joint_map.py --write` instead of hand-editing.
"""

PRIM_PREFIX = "/World/ImportedAsset/"

JOINT_MAP = [
    {"mate_name": "fastened_1", "mate_type": "FASTENED", "body0_path": "/World/ImportedAsset/Base", "body1_path": "/World/ImportedAsset/SupportPost1", "local_pos0": (-0.22709, -0.3048, 0.03175), "local_pos1": (0.28091, -0.0, 0.03175), "local_rot0": (1e-06, 0.0, 0.0, 1.0), "local_rot1": (1.0, 0.0, 0.0, 0.0), "axis": (0.0, 0.0, 1.0)},
    {"mate_name": "fastened_10_loop_closure", "mate_type": "FASTENED", "body0_path": "/World/ImportedAsset/SupportPost1_1", "body1_path": "/World/ImportedAsset/PivotMount_1", "local_pos0": (0.130716, 0.0762, 0.43815), "local_pos1": (0.130716, 0.0762, 0.43815), "local_rot0": (1.0, 0.0, 0.0, 0.0), "local_rot1": (1.0, 0.0, 0.0, 0.0), "axis": (0.0, 0.0, 1.0)},
    {"mate_name": "fastened_12", "mate_type": "FASTENED", "body0_path": "/World/ImportedAsset/SupportPost2", "body1_path": "/World/ImportedAsset/PivotMount_1", "local_pos0": (-0.077208, 0.0762, 0.43562), "local_pos1": (-0.077208, 0.0762, 0.43562), "local_rot0": (1.0, 0.0, 0.0, 0.0), "local_rot1": (1.0, 0.0, 0.0, 0.0), "axis": (0.0, 0.0, 1.0)},
    {"mate_name": "fastened_2", "mate_type": "FASTENED", "body0_path": "/World/ImportedAsset/Base", "body1_path": "/World/ImportedAsset/CenterPost", "local_pos0": (0.02691, -0.3048, 0.03175), "local_pos1": (0.02691, 0.0, 0.03175), "local_rot0": (1e-06, 0.0, 0.0, 1.0), "local_rot1": (1.0, 0.0, 0.0, 0.0), "axis": (0.0, 0.0, 1.0)},
    {"mate_name": "fastened_3", "mate_type": "FASTENED", "body0_path": "/World/ImportedAsset/Base", "body1_path": "/World/ImportedAsset/SupportPost2_1", "local_pos0": (0.28091, -0.3048, 0.03175), "local_pos1": (-0.22709, 0.0, 0.03175), "local_rot0": (1e-06, 0.0, 0.0, 1.0), "local_rot1": (1.0, 0.0, 0.0, 0.0), "axis": (0.0, 0.0, 1.0)},
    {"mate_name": "fastened_4", "mate_type": "FASTENED", "body0_path": "/World/ImportedAsset/SupportPost1", "body1_path": "/World/ImportedAsset/PivotMount", "local_pos0": (0.130716, 0.0762, 0.43815), "local_pos1": (0.130716, 0.0762, 0.43815), "local_rot0": (1.0, 0.0, 0.0, 0.0), "local_rot1": (1.0, 0.0, 0.0, 0.0), "axis": (0.0, 0.0, 1.0)},
    {"mate_name": "fastened_5_loop_closure", "mate_type": "FASTENED", "body0_path": "/World/ImportedAsset/CenterPost", "body1_path": "/World/ImportedAsset/PivotMount", "local_pos0": (0.02691, 0.0762, 0.43815), "local_pos1": (0.02691, 0.076199, 0.43815), "local_rot0": (1.0, 0.0, 0.0, 0.0), "local_rot1": (1.0, 0.0, 0.0, 0.0), "axis": (0.0, 0.0, 1.0)},
    {"mate_name": "fastened_7", "mate_type": "FASTENED", "body0_path": "/World/ImportedAsset/Base", "body1_path": "/World/ImportedAsset/SupportPost2", "local_pos0": (-0.22709, 0.0, 0.03175), "local_pos1": (-0.22709, 0.0, 0.03175), "local_rot0": (1.0, 0.0, 0.0, 0.0), "local_rot1": (1.0, 0.0, 0.0, 0.0), "axis": (0.0, 0.0, 1.0)},
    {"mate_name": "fastened_8", "mate_type": "FASTENED", "body0_path": "/World/ImportedAsset/Base", "body1_path": "/World/ImportedAsset/CenterPost_1", "local_pos0": (0.02691, 0.0, 0.03175), "local_pos1": (0.02691, 0.0, 0.03175), "local_rot0": (1.0, 0.0, 0.0, 0.0), "local_rot1": (1.0, 0.0, 0.0, 0.0), "axis": (0.0, 0.0, 1.0)},
    {"mate_name": "fastened_9", "mate_type": "FASTENED", "body0_path": "/World/ImportedAsset/Base", "body1_path": "/World/ImportedAsset/SupportPost1_1", "local_pos0": (0.28091, 0.0, 0.03175), "local_pos1": (0.28091, 0.0, 0.03175), "local_rot0": (1.0, 0.0, 0.0, 0.0), "local_rot1": (1.0, 0.0, 0.0, 0.0), "axis": (0.0, 0.0, 1.0)},
    {"mate_name": "revolute_1", "mate_type": "REVOLUTE", "body0_path": "/World/ImportedAsset/PivotMount", "body1_path": "/World/ImportedAsset/Axel", "local_pos0": (0.02691, 0.1016, 0.55245), "local_pos1": (0.02691, -0.4318, 0.55245), "local_rot0": (1e-06, 1e-06, 0.707107, 0.707107), "local_rot1": (0.707107, 0.707107, 0.0, 0.0), "axis": (0.0, 0.0, 1.0)},
    {"mate_name": "slider_1", "mate_type": "SLIDER", "body0_path": "/World/ImportedAsset/Axel", "body1_path": "/World/ImportedAsset/Arm", "local_pos0": (0.02691, -0.098806, 0.55245), "local_pos1": (0.02691, -0.0889, 0.55245), "local_rot0": (0.707107, -0.707107, 0.0, 0.0), "local_rot1": (0.707107, -0.707107, 0.0, 0.0), "axis": (0.0, 0.0, 1.0)},
    {"mate_name": "slider_2", "mate_type": "SLIDER", "body0_path": "/World/ImportedAsset/Arm", "body1_path": "/World/ImportedAsset/CounterWeight", "local_pos0": (-0.153058, -0.120396, 0.693871), "local_pos1": (-0.153058, -0.12065, 0.693871), "local_rot0": (0.707107, -0.707107, 0.0, 0.0), "local_rot1": (0.707107, -0.707107, 0.0, 0.0), "axis": (0.0, 0.0, 1.0)},
]
